# Generated by Django 2.0.1 on 2018-01-15 23:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_archivo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.CharField(blank=True, max_length=200)),
                ('fecha_desaparicion', models.CharField(blank=True, max_length=200)),
                ('departamento', models.CharField(blank=True, max_length=200)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('ambiente', models.CharField(blank=True, max_length=200)),
                ('estanteria_no', models.CharField(blank=True, max_length=200)),
                ('plato_no', models.CharField(blank=True, max_length=200)),
                ('caja_no', models.IntegerField(blank=True, null=True)),
                ('legajo_no', models.IntegerField(blank=True, null=True)),
                ('carpeta_no', models.IntegerField(blank=True, null=True)),
                ('descripcion_caso', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Colección',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_la_colección', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_archivo', models.CharField(blank=True, max_length=200)),
                ('localizacion_fisica', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('miniatura', models.URLField(blank=True, null=True)),
                ('caja', models.IntegerField(blank=True, null=True)),
                ('legajo', models.IntegerField(blank=True, null=True)),
                ('carpeta', models.IntegerField(blank=True, null=True)),
                ('número_de_imagen', models.CharField(blank=True, max_length=200)),
                ('fecha_desaparicion', models.CharField(blank=True, max_length=200)),
                ('conteo_de_páginas', models.IntegerField(blank=True, null=True)),
                ('número_de_víctimas', models.IntegerField(blank=True, null=True)),
                ('edad_en_el_momento', models.CharField(blank=True, max_length=200)),
                ('género', models.CharField(blank=True, max_length=200)),
                ('etnicidad', models.CharField(blank=True, max_length=200)),
                ('forma_de_GAM', models.CharField(blank=True, max_length=200)),
                ('policial_o_militar', models.CharField(blank=True, max_length=200)),
                ('tipo_de_violencia', models.CharField(blank=True, max_length=200)),
                ('participación_de_ONG', models.CharField(blank=True, max_length=200)),
                ('profesión', models.CharField(blank=True, max_length=200)),
                ('texto_de_OCR', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_lugar', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manuscrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_manuscrito', models.CharField(max_length=200, null=True)),
                ('imágenes', models.ManyToManyField(blank=True, to='gam_app.Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Organización',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_la_organización', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_la_persona', models.CharField(max_length=200, null=True)),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('apellido_paterno', models.CharField(max_length=200, null=True)),
                ('apellido_materno', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portapapeles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casos', models.ManyToManyField(blank=True, to='gam_app.Caso')),
                ('imágenes', models.ManyToManyField(blank=True, to='gam_app.Imagen')),
                ('manuscrito', models.ManyToManyField(blank=True, to='gam_app.Manuscrito')),
                ('usuario', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transcrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_archivo', models.CharField(max_length=200)),
                ('tiempo_modificado', models.DateTimeField()),
                ('texto_transcrito', ckeditor.fields.RichTextField()),
                ('fun', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='imagen',
            name='actividades_políticas',
            field=models.ManyToManyField(blank=True, to='gam_app.Organización'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='archivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gam_app.Archivo'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='colección',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gam_app.Colección'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='manuscritos',
            field=models.ManyToManyField(blank=True, to='gam_app.Manuscrito'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='persona',
            field=models.ManyToManyField(blank=True, to='gam_app.Persona'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='ubicación_geográfica',
            field=models.ManyToManyField(blank=True, to='gam_app.Lugar'),
        ),
    ]
