# Generated by Django 2.0.1 on 2018-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0002_auto_20180116_0053'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='portapapeles',
#            name='nombre_del_portapapeles',
#            field=models.CharField(blank=True, max_length=200),
#        ),
    ]
