# Generated by Django 2.0.1 on 2018-03-12 17:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0004_imagen_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='notas',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='texto_de_OCR',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
