# Generated by Django 2.0.1 on 2018-03-13 17:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0006_auto_20180313_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpeta_titulo', models.CharField(blank=True, max_length=200)),
                ('nombre_de_la_carpeta', models.CharField(blank=True, max_length=200)),
                ('caja', models.CharField(blank=True, max_length=200)),
                ('legajo', models.CharField(blank=True, max_length=200)),
                ('carpeta', models.CharField(blank=True, max_length=200)),
                ('descripción', ckeditor.fields.RichTextField(blank=True)),
                ('descripción_generada_automaticamente', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
