# Generated by Django 2.0.1 on 2018-06-27 23:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('gam_app', '0014_auto_20180620_2051'),
    ]

    operations = [
    ]
