# Generated by Django 2.1.2 on 2018-11-26 19:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_caso', models.CharField(blank=True, max_length=200)),
                ('slug_name', models.SlugField(blank=True)),
                ('descripción', ckeditor.fields.RichTextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('caso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acceso.Caso')),
            ],
        ),
    ]
