# Generated by Django 2.1.2 on 2018-11-02 14:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gam_app', '0023_auto_20181102_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_caso', models.CharField(blank=True, max_length=200)),
                ('slug_name', models.SlugField()),
                ('descripción', ckeditor.fields.RichTextField(blank=True, default='')),
                ('carpetas', models.ManyToManyField(blank=True, related_name='caso_carpetas', to='gam_app.Carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('caso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acceso.Caso')),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='fotos',
            field=models.ManyToManyField(blank=True, related_name='caso_fotos', to='acceso.Foto'),
        ),
    ]
