# Generated by Django 2.1.2 on 2018-11-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='slug_name',
            field=models.SlugField(blank=True),
        ),
    ]
