# Generated by Django 2.1.2 on 2018-11-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceso', '0001_initial'),
        ('gam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='carpetas',
            field=models.ManyToManyField(blank=True, related_name='caso_carpetas', to='gam_app.Carpeta'),
        ),
        migrations.AddField(
            model_name='caso',
            name='foto_de_perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caso_foto_de_perfil', to='acceso.Foto'),
        ),
        migrations.AddField(
            model_name='caso',
            name='fotos',
            field=models.ManyToManyField(blank=True, related_name='caso_fotos', to='acceso.Foto'),
        ),
    ]
