# Generated by Django 2.1.2 on 2018-11-08 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_auto_20181102_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='foto_de_perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caso_foto_de_perfil', to='acceso.Foto'),
        ),
    ]
