# Generated by Django 2.1.2 on 2019-01-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_auto_20181126_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_filtro', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='fecha_de_desaparicion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='filtros',
            field=models.ManyToManyField(blank=True, related_name='caso_filtros', to='acceso.Filtros'),
        ),
    ]
