# Generated by Django 2.1.2 on 2018-11-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0003_caso_foto_de_perfil'),
    ]

    operations = [
    ]
