# Generated by Django 2.1.2 on 2019-02-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0001_initial'),
        ('acceso', '0003_auto_20190129_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='personas',
            field=models.ManyToManyField(blank=True, related_name='caso_personas', to='gam_app.Persona'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='fecha_de_desaparicion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
