# Generated by Django 2.1.2 on 2018-11-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0004_remove_foto_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
