# Generated by Django 2.0 on 2017-12-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('uuid', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('ocr_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ManyToManyField(blank=True, to='gam_app.Person'),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ManyToManyField(blank=True, to='gam_app.Organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='place',
            field=models.ManyToManyField(blank=True, to='gam_app.Place'),
        ),
    ]
