# Generated by Django 2.0.1 on 2018-01-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portapapeles',
            name='manuscrito',
            field=models.ManyToManyField(blank=True, to='gam_app.Manuscrito'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='caja_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='carpeta_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='legajo_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='caja',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='carpeta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='legajo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='Carpeta',
        ),
        migrations.DeleteModel(
            name='Legajo',
        ),
    ]
