# Generated by Django 2.0 on 2017-12-20 12:34

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gam_app.Archivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.CharField(blank=True, max_length=200)),
                ('fecha_desaparicion', models.CharField(blank=True, max_length=200)),
                ('departamento', models.CharField(blank=True, max_length=200)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('ambiente', models.CharField(blank=True, max_length=200)),
                ('estanteria_no', models.CharField(blank=True, max_length=200)),
                ('plato_no', models.CharField(blank=True, max_length=200)),
                ('caja_no', models.CharField(blank=True, max_length=200)),
                ('legajo_no', models.CharField(blank=True, max_length=200)),
                ('carpeta_no', models.CharField(blank=True, max_length=200)),
                ('descripcion_caso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_location', models.CharField(blank=True, max_length=200)),
                ('date_of_disapearance', models.CharField(blank=True, max_length=200)),
                ('page_count', models.IntegerField(blank=True)),
                ('no_victims', models.IntegerField(blank=True)),
                ('age_at_time', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('ethnicity', models.CharField(blank=True, max_length=200)),
                ('gam_form', models.CharField(blank=True, max_length=200)),
                ('police_military', models.CharField(blank=True, max_length=200)),
                ('kind_of_violence', models.CharField(blank=True, max_length=200)),
                ('ngo_involvement', models.CharField(blank=True, max_length=200)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField()),
                ('case_name', models.ManyToManyField(blank=True, to='gam_app.Person')),
                ('geographic_location', models.ManyToManyField(blank=True, to='gam_app.Place')),
                ('political_activities', models.ManyToManyField(blank=True, to='gam_app.Organization')),
            ],
        ),
        migrations.RenameField(
            model_name='document',
            old_name='location',
            new_name='box',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uuid',
            new_name='bundle',
        ),
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.RemoveField(
            model_name='document',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='document',
            name='place',
        ),
        migrations.AddField(
            model_name='document',
            name='collection',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='physical_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='archivo',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gam_app.Archivo'),
            preserve_default=False,
        ),
    ]
