# Generated by Django 2.0.1 on 2018-01-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcrito',
            name='fun',
        ),
        migrations.AlterField(
            model_name='caso',
            name='caja_no',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caso',
            name='carpeta_no',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caso',
            name='legajo_no',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagen',
            name='caja',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagen',
            name='carpeta',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagen',
            name='legajo',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
    ]
