# Generated by Django 2.0.1 on 2018-07-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0001_initial'),
    ]

    operations = [
    ]
