# Generated by Django 2.0.1 on 2018-07-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0002_auto_20180711_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='organization_status',
            field=models.CharField(choices=[('NONE', 'Sin correcciones'), ('IN', 'En progreso'), ('DONE', 'Compitió'), ('FINAL', 'Competido y verificado')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='person_status',
            field=models.CharField(choices=[('NONE', 'Sin correcciones'), ('IN', 'En progreso'), ('DONE', 'Compitió'), ('FINAL', 'Competido y verificado')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='place_status',
            field=models.CharField(choices=[('NONE', 'Sin correcciones'), ('IN', 'En progreso'), ('DONE', 'Compitió'), ('FINAL', 'Competido y verificado')], default='NONE', max_length=20),
        ),
    ]
