# Generated by Django 2.0 on 2018-01-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0002_auto_20180108_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='manuscrito',
            new_name='manuscritos',
        ),
        migrations.RemoveField(
            model_name='portapapeles',
            name='manuscritos',
        ),
        migrations.AddField(
            model_name='manuscrito',
            name='imágenes',
            field=models.ManyToManyField(blank=True, to='gam_app.Imagen'),
        ),
    ]
