# Generated by Django 2.0.1 on 2018-06-28 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0002_remove_persona_relaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='relaciones',
        ),
    ]
