# Generated by Django 2.0 on 2017-12-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0002_auto_20171220_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='document',
            name='level',
        ),
        migrations.RemoveField(
            model_name='document',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='document',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='document',
            name='archivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
