# Generated by Django 2.0 on 2018-01-08 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0003_auto_20180108_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_archivo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Colección',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_la_colección', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='imagen',
            old_name='forma_de_gam',
            new_name='forma_de_GAM',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='archivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gam_app.Archivo'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='colección',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gam_app.Colección'),
        ),
    ]
