# Generated by Django 2.0.1 on 2018-02-23 14:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0003_portapapeles_nombre_del_portapapeles'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='notas',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
