# Generated by Django 2.0.1 on 2018-07-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0003_auto_20180715_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='status',
            field=models.CharField(blank=True, choices=[('NONE', 'Sin correcciones'), ('IN', 'En progreso'), ('DONE', 'Compitió'), ('FINAL', 'Competido y verificado')], max_length=20),
        ),
    ]
