# Generated by Django 2.0.1 on 2018-06-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0003_remove_persona_relaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='status',
            field=models.CharField(choices=[('NONE', 'Sin correcciones'), ('IN', 'En progreso'), ('DONE', 'Compitió'), ('FINAL', 'Competido y verificado')], max_length=20),
        ),
    ]
