# Generated by Django 2.0.1 on 2018-07-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0004_auto_20180628_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='status',
            field=models.CharField(choices=[('NONE', 'Sin correcciones'), ('IN', 'En progreso'), ('DONE', 'Compitió'), ('FINAL', 'Competido y verificado')], default='NONE', max_length=20),
        ),
    ]
