# Generated by Django 2.0.1 on 2018-07-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0004_auto_20180723_1411'),
    ]

    operations = [
    ]
