# Generated by Django 2.0 on 2017-12-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0004_auto_20171222_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='physical_location',
            new_name='filename',
        ),
    ]
