# Generated by Django 2.0.1 on 2018-07-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0005_auto_20180726_1838'),
    ]

    operations = [
    ]
