# Generated by Django 2.0.1 on 2018-03-13 17:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0005_auto_20180312_1738'),
    ]

    operations = [
    ]
