# Generated by Django 2.0 on 2017-12-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0005_auto_20171222_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Database',
            new_name='Caso',
        ),
    ]
