# Generated by Django 2.0 on 2017-12-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0006_auto_20171222_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='filename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gam_app.Document'),
        ),
    ]
