# Generated by Django 2.0.1 on 2018-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0006_auto_20180727_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sites',
            new_name='site',
        ),
    ]
