# Generated by Django 2.0.1 on 2018-07-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0007_auto_20180730_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='segundos_nombre',
            new_name='segundo',
        ),
    ]
