# Generated by Django 2.0.1 on 2018-03-13 17:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0007_auto_20180313_1723'),
    ]

    operations = [
    ]
