# Generated by Django 2.0 on 2017-12-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0008_auto_20171228_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='case_name',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='geographic_location',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='political_activities',
        ),
        migrations.AddField(
            model_name='document',
            name='age_at_time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='date_of_disapearance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='gam_form',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='gender',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='geographic_location',
            field=models.ManyToManyField(blank=True, to='gam_app.Place'),
        ),
        migrations.AddField(
            model_name='document',
            name='kind_of_violence',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='ngo_involvement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='no_victims',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='page_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='police_military',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='political_activities',
            field=models.ManyToManyField(blank=True, to='gam_app.Organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='profession',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Metadata',
        ),
    ]
