# Generated by Django 2.0 on 2017-12-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0009_auto_20171228_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='person',
            field=models.ManyToManyField(blank=True, to='gam_app.Person'),
        ),
    ]
