# Generated by Django 2.0.1 on 2018-06-14 18:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0009_auto_20180403_1821'),
    ]

    operations = [
    ]
