# Generated by Django 2.0.1 on 2018-06-19 15:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0010_auto_20180614_1853'),
    ]

    operations = [
    ]
