# Generated by Django 2.0 on 2017-12-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0010_document_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='no_victims',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
