# Generated by Django 2.0.1 on 2018-09-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0010_auto_20180730_1935'),
    ]

    operations = [
    ]
