# Generated by Django 2.0 on 2018-01-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0011_auto_20171230_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dzi',
            field=models.URLField(blank=True, null=True),
        ),
    ]
