# Generated by Django 2.0.1 on 2018-09-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0012_auto_20180921_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='image',
            field=models.ManyToManyField(blank=True, to='gam_app.Imagen'),
        ),
        migrations.AddField(
            model_name='organización',
            name='image',
            field=models.ManyToManyField(blank=True, to='gam_app.Imagen'),
        ),
        migrations.AddField(
            model_name='persona',
            name='image',
            field=models.ManyToManyField(blank=True, to='gam_app.Imagen'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gam_app.Item'),
        ),
    ]
