# Generated by Django 2.0.8 on 2018-10-12 18:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0013_auto_20180928_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='punto',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
