# Generated by Django 2.0.1 on 2018-06-20 20:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0013_auto_20180619_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='status',
            field=models.CharField(choices=[('NONE', 'Sin correcciones'), ('IN', 'En progreso'), ('DONE', 'Compitió'), ('FINAL', 'Competido y verificado')], default='NONE', max_length=20)
     ),
    ]
