# Generated by Django 2.0.8 on 2018-10-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0014_auto_20181012_1811'),
    ]

    operations = [
    ]
