# Generated by Django 2.0.8 on 2018-10-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0015_auto_20181023_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relación',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=200, null=True)),
                ('personA', models.ManyToManyField(related_name='A', to='gam_app.Persona')),
                ('personB', models.ManyToManyField(related_name='B', to='gam_app.Persona')),
            ],
        ),
    ]
