# Generated by Django 2.0.8 on 2018-10-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0016_auto_20181023_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relación',
            old_name='personA',
            new_name='persona_A',
        ),
        migrations.RenameField(
            model_name='relación',
            old_name='personB',
            new_name='persona_B',
        ),
        migrations.RenameField(
            model_name='relación',
            old_name='relationship',
            new_name='relación',
        ),
    ]
