# Generated by Django 2.0.8 on 2018-10-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0017_auto_20181023_1300'),
    ]

    operations = [
    ]
