# Generated by Django 2.0.8 on 2018-10-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0019_auto_20181023_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('número_de_caja', models.CharField(blank=True, max_length=200)),
                ('municipios', models.CharField(blank=True, max_length=200)),
                ('letras', models.CharField(blank=True, max_length=200)),
                ('legajos', models.CharField(blank=True, max_length=200)),
                ('fechas_extremas', models.CharField(blank=True, max_length=200)),
                ('volumen_en_metros_lineales', models.CharField(blank=True, max_length=200)),
                ('sistema_digital', models.CharField(blank=True, max_length=200)),
                ('archivo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gam_app.Archivo')),
                ('colección', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gam_app.Colección')),
                ('departamento', models.ManyToManyField(blank=True, to='gam_app.Lugar')),
                ('carpetas', models.ManyToManyField(blank=True, to='gam_app.Carpeta')),
            ],
        ),
    ]
