# Generated by Django 2.0.8 on 2018-10-23 15:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0020_auto_20181023_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='descripción',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
