# Generated by Django 2.1.2 on 2018-10-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0021_auto_20181023_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='carpetas',
            field=models.ManyToManyField(blank=True, related_name='carpetas', to='gam_app.Carpeta'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='departamento',
            field=models.ManyToManyField(blank=True, related_name='departamento', to='gam_app.Lugar'),
        ),
        migrations.RemoveField(
            model_name='caja',
            name='municipios',
        ),
        migrations.AddField(
            model_name='caja',
            name='municipios',
            field=models.ManyToManyField(blank=True, related_name='municipios', to='gam_app.Lugar'),
        ),
    ]
