# Generated by Django 2.1.2 on 2018-11-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0022_auto_20181029_1748'),
    ]

    operations = [
    ]
