# Generated by Django 2.1.2 on 2018-11-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0023_auto_20181102_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='actividades_políticas',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='conteo_de_páginas',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='edad_en_el_momento',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='etnicidad',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='fecha_desaparicion',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='género',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='manuscritos',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='miniatura',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='número_de_víctimas',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='participación_de_ONG',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='policial_o_militar',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='profesión',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='tipo_de_violencia',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='ubicación_geográfica',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='url',
        ),
        migrations.RemoveField(
            model_name='item',
            name='imágenes',
        ),
        migrations.AddField(
            model_name='carpeta',
            name='organización',
            field=models.ManyToManyField(blank=True, to='gam_app.Organización'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='organization_status',
            field=models.CharField(choices=[('NONE', 'Sin correcciones'), ('IN', 'En progreso'), ('DONE', 'Compitió'), ('FINAL', 'Competido y verificado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='person_status',
            field=models.CharField(choices=[('NONE', 'Sin correcciones'), ('IN', 'En progreso'), ('DONE', 'Compitió'), ('FINAL', 'Competido y verificado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='place_status',
            field=models.CharField(choices=[('NONE', 'Sin correcciones'), ('IN', 'En progreso'), ('DONE', 'Compitió'), ('FINAL', 'Competido y verificado')], max_length=20, null=True),
        ),
    ]
