# Generated by Django 2.1.2 on 2018-11-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0024_auto_20181108_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='organization_status',
            field=models.CharField(blank=True, choices=[('NONE', 'Sin correcciones'), ('IN', 'En progreso'), ('DONE', 'Compitió'), ('FINAL', 'Competido y verificado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='person_status',
            field=models.CharField(blank=True, choices=[('NONE', 'Sin correcciones'), ('IN', 'En progreso'), ('DONE', 'Compitió'), ('FINAL', 'Competido y verificado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='place_status',
            field=models.CharField(blank=True, choices=[('NONE', 'Sin correcciones'), ('IN', 'En progreso'), ('DONE', 'Compitió'), ('FINAL', 'Competido y verificado')], max_length=20, null=True),
        ),
    ]
